# Generated by Django 5.1 on 2025-01-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bom_app", "0003_alter_item_type_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
